String columnTypes = "#JCAT  String\n"+
"Satcat  int\n"+
"Piece  String\n"+
"Type  String\n"+
"Name  String\n"+
"PLName  String\n"+
"LDate  Date\n"+
"Parent  String\n"+
"SDate  Date\n"+
"Primary  String\n"+
"DDate  Date\n"+
"Status  String\n"+
"Dest  String\n"+
"Owner  String\n"+
"State  String\n"+
"Manufacturer  String\n"+
"Bus  String\n"+
"Motor  String\n"+
"Mass  float\n"+
"MassFlag  boolean\n"+
"DryMass  float\n"+
"DryFlag  boolean\n"+
"TotMass  float\n"+
"TotFlag  boolean\n"+
"Length  float\n"+
"LFlag  boolean\n"+
"Diameter  float\n"+
"DFlag  boolean\n"+
"Span  float\n"+
"SpanFlag  boolean\n"+
"Shape  String\n"+
"ODate  Date\n"+
"Perigee  int\n"+
"PF  boolean\n"+
"Apogee  int\n"+
"AF  boolean\n"+
"Inc  float\n"+
"IF  boolean\n"+
"OpOrbit  String\n"+
"OQUAL  String\n"+
"AltNames  String\n";
